<?php $this->layout('layout::default', ['title' => 'Contributor code of conduct']) ?>

<a href="#top" class="text-muted back-to-top"><em class="fa fa-toggle-up"></em>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('layout::nav') ?>
                        <div class="repository-content content">
                            <div class="box box-condensed">
                                <div class="box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="en" class="anchor" aria-hidden="true" href="#en">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            <img class="flag" src="/assets/images/reino-unido.png">Contributor code of conduct
                                        </h1>
                                        <p>This project adheres to <a href="http://codemanifesto.com" target="_blank" rel="noopener">the code manifesto</a>.</p>
                                        <h2 id="the-code-manifesto">The Code Manifesto</h2>
                                        <p>We want to work in an ecosystem that empowers developers to reach their potential--one that encourages growth and effective collaboration. A space that is safe for all.</p>
                                        <p>A space such as this benefits everyone that participates in it. It encourages new developers to enter our field. It is through discussion and collaboration that we grow, and through growth that we improve.</p>
                                        <p>In the effort to create such a place, we hold to these values:</p>
                                        <ol>
                                            <li><strong>Discrimination limits us.</strong> This includes discrimination on the basis of race, gender, sexual orientation, gender identity, age, nationality, technology and any other arbitrary exclusion of a group of people.</li>
                                            <li><strong>Boundaries honor us.</strong> Your comfort levels are not everyone’s comfort levels. Remember that, and if brought to your attention, heed it.</li>
                                            <li><strong>We are our biggest assets.</strong> None of us were born masters of our trade. Each of us has been helped along the way. Return that favor, when and where you can.</li>
                                            <li><strong>We are resources for the future.</strong> As an extension of #3, share what you know. Make yourself a resource to help those that come after you.</li>
                                            <li><strong>Respect defines us.</strong> Treat others as you wish to be treated. Make your discussions, criticisms and debates from a position of respectfulness. Ask yourself, is it true? Is it necessary? Is it constructive? Anything less is unacceptable.</li>
                                            <li><strong>Reactions require grace.</strong> Angry responses are valid, but abusive language and vindictive actions are toxic. When something happens that offends you, handle it assertively, but be respectful. Escalate reasonably, and try to allow the offender an opportunity to explain themselves, and possibly correct the issue.</li>
                                            <li><strong>Opinions are just that: opinions.</strong> Each and every one of us, due to our background and upbringing, have varying opinions. That is perfectly acceptable. Remember this: if you respect your own opinions, you should respect the opinions of others.</li>
                                            <li><strong>To err is human.</strong> You might not intend it, but mistakes do happen and contribute to build experience. Tolerate honest mistakes, and don't hesitate to apologize if you make one yourself.</li>
                                        </ol>
                                    </article>
                                </div>
                                <div class="box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="pt-br" class="anchor" aria-hidden="true" href="#pt-br">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            <img class="flag" src="/assets/images/brasil.png">Código de conduta do colaborador
                                        </h1>
                                        <p>Este projeto adere ao <a href="http://codemanifesto.com" target="_blank" rel="noopener">the code manifesto</a>.</p>
                                        <h2 id="manifesto-do-codigo">Manifesto do código</h2>
                                        <p>Queremos trabalhar em um ecossistema que capacita desenvolvedores a atingir todo seu potencial, que encoraja crescimento e colaboração. Um espaço que seja seguro para todos.</p>
                                        <p>Um espaço como este beneficia a todos que dele participam. Encoraja novos desenvolvedores a entrar em nosso campo. É através da discussão e colaboração que nós crescemos, e através do crescimento que nós melhoramos.</p>
                                        <p>No esforço de criar tal lugar, sustentamos estes valores:</p>
                                        <ol>
                                            <li><strong>Discriminação nos limita.</strong> Isso inclui a discriminação com base em raça, sexo, orientação sexual, identidade de gênero, idade, nacionalidade ou qualquer outra exclusão arbitrária de um grupo de pessoas.</li>
                                            <li><strong>Limites nos honram.</strong> Seus níveis de conforto não são os níveis de conforto de todos. Lembre-se disso e, se alguém chamar a sua atenção, acate.</li>
                                            <li><strong>Somos nosso maior patrimônio.</strong> Nenhum de nós nasceu mestre. Cada um de nós foi ajudado durante o caminho, devolva o favor, quando e onde puder.</li>
                                            <li><strong>Somos recursos para o futuro.</strong> Uma extensão do item #3, compartilhe seu conhecimento. Transforme-se em um recurso de auxílio àqueles que vierem depois de você.</li>
                                            <li><strong>Respeito nos define.</strong> Trate os outros como gostaria de ser tratado. Discuta, critique e debata respeitosamente. Pergunte-se: isso é verdade? Isso é necessário? Isso é construtivo? Qualquer outra coisa não é tolerável.</li>
                                            <li><strong>Reações requerem bondade.</strong> Respostas raivosas são válidas, mas o uso de linguagem abusiva e vingativa é tóxico. Quando algo ofensivo acontecer a você, lide com isso de forma assertiva, mas sendo respeitoso. Seja razoável, dando a oportunidade à pessoa que o ofendeu de explicar-se, e, se possível, corrigir o problema.</li>
                                            <li><strong>As opiniões são apenas isso: opiniões.</strong> Todos e cada um de nós, devido à nossa formação e educação, têm diferentes opiniões. De fato, isso é perfeitamente aceitável. Lembre-se: se você respeitar suas próprias opiniões, você deve respeitar as opiniões dos outros.</li>
                                            <li><strong>Errar é humano.</strong> Você pode não querer, mas erros acontecem. Tolere erros genuínos e não hesite em se desculpar se você fizer o mesmo.</li>
                                        </ol>
                                    </article>
                                </div>
                                <div class="box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="es" class="anchor" aria-hidden="true" href="#es">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            <img class="flag" src="/assets/images/espanha.png">Código de conducta del colaborador
                                        </h1>
                                        <p>Este proyecto se adhiere a <a href="http://codemanifesto.com" target="_blank" rel="noopener">the code manifesto</a>.</p>
                                        <h2 id="el-manifiesto-del-codigo">Code Manifesto: El Manifiesto del Código</h2>
                                        <p>Queremos trabajar en un ecosistema que permita a los desarrolladores explotar su potencial, que aliente el crecimiento profesional y la colaboración. Un espacio seguro para todos.</p>
                                        <p>Un espacio como este beneficia a todos los que participen en él. Motiva a los nuevos desarrolladores a entrar a nuestro campo profesional. Es a través de la discusión y la colaboración que crecemos, y a través del crecimiento que mejoramos.</p>
                                        <p>En el esfuerzo por crear tal espacio, sostenemos estos valores:</p>
                                        <ol>
                                            <li><strong>La Discriminación nos limita.</strong> Esto incluye discriminación por motivos de raza, género, orientación sexual, la identidad de género, edad, nacionalidad, tecnología o cualquier otra exclusión arbitraria de un grupo de personas.</li>
                                            <li><strong>Los Límites nos honran.</strong> Los niveles de confort de cada uno son distintos. Recuérdalo, y si llama tu atención, atiéndelo.</li>
                                            <li><strong>Somos nuestro activo principal.</strong> Ninguno de nosotros nació siendo un maestro en nuestro negocio. Cada uno de nosotros ha recibido ayuda a lo largo de su camino. Devuelve el favor, cuando y donde puedas.</li>
                                            <li><strong>Somos recursos para el futuro.</strong> Como una extensión de #3, comparte lo que sabes. Sé un recurso de ayuda para quienes lo necesiten.</li>
                                            <li><strong>El Respeto nos define.</strong> Trata a otros como quieras ser tratado. Conduce tus discusiones, críticas y debates desde el respeto. Pregúntate, ¿Es esto cierto, necesario o constructivo? Cualquier actitud menor es intolerable.</li>
                                            <li><strong>Las Malas Reacciones requieren gracia.</strong> Los exabruptos son válidos, pero el lenguaje abusivo y las acciones vengativas son tóxicos. Cuando suceda algo que te ofenda, manéjalo con firmeza, pero se respetuoso. Escala razonablemente, y trata de dar la oportunidad a quien causó la ofensa de explicarse, y posiblemente de corregir el problema.</li>
                                            <li><strong>Las opiniones son sólo eso: opiniones.</strong> Todos y cada uno de nosotros tenemos diferentes opiniones, debido a nuestros antecedentes y nuestra crianza. Esto es perfectamente aceptable. Recuerda esto: si respetas tus propias opiniones, debes respetar las opiniones de los demás.</li>
                                            <li><strong>Errar es humano.</strong> Los errores suceden y contribuyen a aumentar nuestra experiencia, por más que no sea nuestra intención cometerlos. Tolera equivocaciones honestas y no dudes en pedir disculpas si tú cometes una.</li>
                                        </ol>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
