<?php $this->layout('layout::default', ['title' => 'License']) ?>

<a href="#top" class="text-muted back-to-top"><em class="fa fa-toggle-up"></em>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('layout::nav') ?>
                        <div class="repository-content content">
                            <div class="box box-condensed">
                                <div class="box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="en" class="anchor" aria-hidden="true" href="#en">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            License
                                        </h1>
                                        <p><strong>Copyright &copy; <?= date('Y') ?>, Nuvemshop</strong></p>
                                        <p>All rights reserved.</p>
                                        <p>We do not want anyone to see our source description, but if for any reason our description is stolen or otherwise obtained, the manufacturer reserve all rights, such as rights under intellectual property laws. The manufacturer does not give you any right to, and you may not:</p>
                                        <p>(i) use or virtualize features of the software separately;</p>
                                        <p>(ii) publish, copy, rent, lease, or lend the software;</p>
                                        <p>(iii) transfer the software;</p>
                                        <p>(iv) work around any technical restrictions or limitations in the software;</p>
                                        <p>(v) use the software as server software, for commercial hosting, make the software available for simultaneous use by multiple users over a network, install the software on a server and allow users to access it remotely, or install the software on a device for use only by remote users;</p>
                                        <p>(vi) reverse engineer, decompile, or disassemble the software, or attempt to do so.</p>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
