<?php $this->layout('layout::default', ['title' => 'Setup']) ?>

<a href="#top" class="text-muted back-to-top"><em class="fa fa-toggle-up"></em>&nbsp;Back to top</a>
<div class="content">
    <div itemtype="http://schema.org/SoftwareSourceCode">
        <main>
            <div class="px-3">
                <div class="container-fluid">
                    <div class="row">
                        <?= $this->insert('layout::nav') ?>
                        <div class="repository-content content">
                            <div class="box box-condensed">
                                <div class="box-body p-5">
                                    <article class="markdown-body container-lg" itemprop="text">
                                        <h1>
                                            <a id="en" class="anchor" aria-hidden="true" href="#en">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            Development environment setup
                                        </h1>
                                        <p>Learn about the requirements and setup of a development environment to enable project contribution.</p>
                                        <h2>
                                            <a id="requirements" class="anchor" aria-hidden="true" href="#requirements">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            Requirements
                                        </h2>
                                        <ul>
                                            <li><a href="https://www.docker.com/" target="_blank" rel="noopener"><strong>Docker</strong></a></li>
                                            <li><a href="https://docs.docker.com/compose/install/" target="_blank" rel="noopener"><strong>Docker Compose</strong></a></li>
                                        </ul>
                                        <h2>
                                            <a id="settings" class="anchor" aria-hidden="true" href="#settings">
                                                <svg class="octicon octicon-link" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
                                                    <path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path>
                                                </svg>
                                            </a>
                                            Settings
                                        </h2>
                                        <p>The application provides a <code>compose.yaml</code> for use with <a href="https://docs.docker.com/compose/" target="_blank" rel="noopener">docker-compose</a>.</p>
                                        <p>Build and launch the images by running the script:</p>
                                        <div class="highlight highlight-source-shell">
                                            <pre><span class="code-number">1 </span><span class="code-text">$ sudo ./bin/runenv.sh</span></pre>
                                        </div>
                                        <p>The following services will be performed:</p>
                                        <ul>
                                            <li><code><strong>services-custom-fields-nginx</strong>: image: nginx:alpine</code></li>
                                            <li><code><strong>services-custom-fields-php</strong>: image: php:8.2.7-fpm-alpine</code></li>
                                            <li><code><strong>services-custom-fields-elk</strong>: image: sebp/elk:latest</code></li>
                                        </ul>
                                        <p>After the image provisioning confirmation message, you can visit <a href="http://localhost:8181" rel="noopener">http://localhost:8181</a> (HTTP/HTTP1.1) or <a href="https://localhost:8282" rel="noopener">https://localhost:8282</a> (HTTPS/HTTP2.0) to test the environment setup.</p>
                                        <p>If everything went well, voilà, you are ready to use the application!</p>
                                    </article>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
