name: services-custom-fields
services :
  nginx :
    build :
      context : .
      dockerfile : ./environment/nginx/Dockerfile
    container_name : services-custom-fields-nginx
    ports :
      - "8181:80"
      - "8282:443"
      - "8383:9001"
    privileged : true
    volumes :
      - "./environment/nginx/log:/var/log/nginx"
    command: [nginx-debug, '-g', 'daemon off;']
  php :
    build :
      context : .
      dockerfile : ./environment/php/Dockerfile
      target: final
    container_name : services-custom-fields-php
    privileged : true
    volumes :
      - "./:/var/www"
      - "./environment/php/log:/var/log"
  elk:
    image: sebp/elk:latest
    container_name: services-custom-fields-elk
    ports:
      - "5601:5601"
      - "9200:9200"
    environment:
      TZ: America/Sao_Paulo
      KIBANA_USER: kibana
      KIBANA_PASSWORD: s0m3C0mpl3xP@ssw0rd!
      LOGSTASH_START: 0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - "./environment/elk/log:/var/log/elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2g
