name: services-custom-fields
services :
  nginx :
    build :
      context : .
      dockerfile : ./environment/nginx/Dockerfile
    container_name : services-custom-fields-nginx
    ports :
      - "8181:80"
      - "8282:443"
      - "8383:9001"
    privileged : true
    volumes :
      - "./environment/nginx/log:/var/log/nginx"
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - elk-php
  php :
    build :
      context : .
      dockerfile : ./environment/php/Dockerfile
      target: final
    container_name : services-custom-fields-php
    privileged : true
    volumes :
      - "./:/var/www"
      - "./environment/php/log:/var/log"
    networks:
      - elk-php
  elk:
    image: sebp/elk:latest
    container_name: services-custom-fields-elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      TZ: America/Sao_Paulo
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: s0m3C0mpl3xP@ssw0rd!
      LOGSTASH_USER: elastic
      LOGSTASH_PASSWORD: s0m3C0mpl3xP@ssw0rd!
      KIBANA_USER: kibana
      KIBANA_PASSWORD: s0m3C0mpl3xP@ssw0rd!
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4Gb
    networks:
      - elk-php
networks:
  elk-php:
    driver: bridge