<pre>
<span class="code-number">01</span> <span class="code-text">type: summarize changes in around 50 characters</span>
<span class="code-number">02</span> <span class="code-text"></span>
<span class="code-number">03</span> <span class="code-text">More detailed explanatory text, if necessary. Wrap it to about 72</span>
<span class="code-number">04</span> <span class="code-text">characters or so. In some contexts, the first line is treated as the</span>
<span class="code-number">05</span> <span class="code-text">subject of the commit and the rest of the text as the body. The</span>
<span class="code-number">06</span> <span class="code-text">blank line separating the summary from the body is critical (unless</span>
<span class="code-number">07</span> <span class="code-text">you omit the body entirely); various tools like `log`, `shortlog`</span>
<span class="code-number">08</span> <span class="code-text">and `rebase` can get confused if you run the two together.</span>
<span class="code-number">09</span> <span class="code-text"></span>
<span class="code-number">10</span> <span class="code-text">Explain the problem that this commit is solving. Focus on why you</span>
<span class="code-number">11</span> <span class="code-text">are making this change as opposed to how (the code explains that).</span>
<span class="code-number">12</span> <span class="code-text">Are there side effects or other unintuitive consequences of this</span>
<span class="code-number">13</span> <span class="code-text">change? Here's the place to explain them.</span>
<span class="code-number">14</span> <span class="code-text"></span>
<span class="code-number">15</span> <span class="code-text">Further paragraphs come after blank lines.</span>
<span class="code-number">16</span> <span class="code-text"></span>
<span class="code-number">17</span> <span class="code-text"> - Bullet points are okay, too</span>
<span class="code-number">18</span> <span class="code-text"> - Typically a hyphen or asterisk is used for the bullet, preceded</span>
<span class="code-number">19</span> <span class="code-text">   by a single space, with blank lines in between, but conventions</span>
<span class="code-number">20</span> <span class="code-text">   vary here</span>
<span class="code-number">21</span> <span class="code-text"></span>
<span class="code-number">22</span> <span class="code-text">If you use an issue tracker, put references to them at the bottom,</span>
<span class="code-number">23</span> <span class="code-text">like this:</span>
<span class="code-number">25</span> <span class="code-text"></span>
<span class="code-number">26</span> <span class="code-text">Resolves: CRBU-1984 #time 5m</span>
<span class="code-number">26</span> <span class="code-text">See also: CRBU-2023, CRBU-2024</span>
</pre>

