<pre>
<span class="code-number">1</span> <span class="code-text"># Bad</span>
<span class="code-number">2</span> <span class="code-text">ababab refactor: agregue el método "use" al modelo de crédito</span>
<span class="code-number">3</span> <span class="code-text">efefef refactor: usa o InventoryBackendPool para recuperar o backend de estoque</span>
<span class="code-number">4</span> <span class="code-text">bebebe fix: fix method name of InventoryBackend child classes</span>
</pre>

