<pre>
<span class="code-number">1</span> <span class="code-text">&lt;tipo&gt;(&lt;escopo opcional&gt;): &lt;descrição&gt;</span>
<span class="code-number">2</span> <span class="code-comment">LINHA EM BRANCO</span>
<span class="code-number">3</span> <span class="code-text">&lt;corpo&gt;</span>
<span class="code-number">4</span> <span class="code-comment">LINHA EM BRANCO</span>
<span class="code-number">5</span> <span class="code-text">&lt;rodapé&gt;</span>
</pre>
