<pre>
<span class="code-number">1</span> <span class="code-text"># Bom</span>
<span class="code-number">2</span> <span class="code-text">refactor: adiciona o método `use` na classe Credit</span>
<span class="code-number">3</span> <span class="code-text"></span>
<span class="code-number">4</span> <span class="code-text">Alterado de namedtuple para classe porque nós precisamos</span>
<span class="code-number">5</span> <span class="code-text">configurar um novo atributo (in_use_amount) com um novo valor.</span>
</pre>

