<pre>
<span class="code-number">1</span> <span class="code-text"># Bom</span>
<span class="code-number">2</span> <span class="code-text">fix: corrige o nome do método das classes filhas de InventoryBackend</span>
<span class="code-number">3</span> <span class="code-text"></span>
<span class="code-number">4</span> <span class="code-text">As classes derivadas do Inventory Backend não respeitavam a interface da</span>
<span class="code-number">5</span> <span class="code-text">classe base.</span>
<span class="code-number">6</span> <span class="code-text"></span>
<span class="code-number">7</span> <span class="code-text">Funcionava anteriormente porque o carrinho estava chamando a</span>
<span class="code-number">8</span> <span class="code-text">implementação incorretamente.</span>
</pre>

