<pre>
<span class="code-number">1</span> <span class="code-text"># Good</span>
<span class="code-number">2</span> <span class="code-text">refactor: add `use` method in Credit class</span>
<span class="code-number">3</span> <span class="code-text"></span>
<span class="code-number">4</span> <span class="code-text">Changed from namedtuple to class because we need to set a new attribute</span>
<span class="code-number">5</span> <span class="code-text">(in_use_amount) with a new value.</span>
</pre>

