<pre>
<span class="code-number">1</span> <span class="code-text">fix(order/update): ajusta el argumento de la función changeStatus</span>
<span class="code-number">2</span> <span class="code-text"></span>
<span class="code-number">3</span> <span class="code-text">El método changeStatus estaba recibiendo el argumento XPTO.</span>
<span class="code-number">4</span> <span class="code-text">Ahora recibe el argumento correcto: FOO.</span>
<span class="code-number">5</span> <span class="code-text"></span>
<span class="code-number">6</span> <span class="code-text">CRBU-1984 #time 5m</span>
</pre>

