<pre>
<span class="code-number">1</span> <span class="code-text">&lt;type&gt;(&lt;optional scope&gt;): &lt;subject&gt;</span>
<span class="code-number">2</span> <span class="code-comment">BLANK LINE</span>
<span class="code-number">3</span> <span class="code-text">&lt;body&gt;</span>
<span class="code-number">4</span> <span class="code-comment">BLANK LINE</span>
<span class="code-number">5</span> <span class="code-text">&lt;footer&gt;</span>
</pre>
