<pre>
<span class="code-number">1</span> <span class="code-text">fix(order/update): adjust the changeStatus function argument</span>
<span class="code-number">2</span> <span class="code-text"></span>
<span class="code-number">3</span> <span class="code-text">The changeStatus method was receiving XPTO argument.</span>
<span class="code-number">4</span> <span class="code-text">Now receives the correct argument: FOO.</span>
<span class="code-number">5</span> <span class="code-text"></span>
<span class="code-number">6</span> <span class="code-text">CRBU-1984 #time 5m</span>
</pre>

