<pre>
<span class="code-number">1</span> <span class="code-text">&lt;tipo&gt;(&lt;alcance opcional>;): &lt;descripción&gt;</span>
<span class="code-number">2</span> <span class="code-comment">LINEA EN BLANCO</span>
<span class="code-number">3</span> <span class="code-text">&lt;cuerpo&gt;</span>
<span class="code-number">4</span> <span class="code-comment">LINEA EN BLANCO</span>
<span class="code-number">5</span> <span class="code-text">&lt;zócalo&gt;</span>
</pre>
