<pre>
<span class="code-number">1</span> <span class="code-text"># Good</span>
<span class="code-number">2</span> <span class="code-text">ababab refactor: adiciona o método `use` ao model Credit</span>
<span class="code-number">3</span> <span class="code-text">efefef refactor: usa o InventoryBackendPool para recuperar o backend de estoque</span>
<span class="code-number">4</span> <span class="code-text">bebebe fix: corrige nome de método na classe InventoryBackend</span>
</pre>

