<pre>
<span class="code-number">01</span> <span class="code-text">tipo: resuma as mudanças em cerca de 50 caracteres</span>
<span class="code-number">02</span> <span class="code-text"></span>
<span class="code-number">03</span> <span class="code-text">Texto explicativo mais detalhado, se necessário. Envolva-o em cerca de</span>
<span class="code-number">04</span> <span class="code-text">72 caracteres ou mais. Em alguns contextos, a primeira linha é tratada</span>
<span class="code-number">05</span> <span class="code-text">como assunto do commit e o restante do texto como corpo. A linha em</span>
<span class="code-number">06</span> <span class="code-text">branco que separa o resumo do corpo é crítica (a menos que você omita</span>
<span class="code-number">07</span> <span class="code-text">totalmente o corpo); várias ferramentas como `log`, `shortlog` e</span>
<span class="code-number">08</span> <span class="code-text">`rebase` podem ficar confusas se você executar os dois juntos.</span>
<span class="code-number">09</span> <span class="code-text"></span>
<span class="code-number">10</span> <span class="code-text">Explique o problema que este commit está resolvendo. Concentre-se no</span>
<span class="code-number">11</span> <span class="code-text">motivo pelo qual você está fazendo essa alteração e não em como (o</span>
<span class="code-number">12</span> <span class="code-text">código explica isso). Existem efeitos colaterais ou outras consequências</span>
<span class="code-number">13</span> <span class="code-text">não intuitivas dessa mudança? Aqui é o lugar para explicá-los.</span>
<span class="code-number">14</span> <span class="code-text"></span>
<span class="code-number">15</span> <span class="code-text">Os parágrafos seguintes vêm após as linhas em branco.</span>
<span class="code-number">16</span> <span class="code-text"></span>
<span class="code-number">17</span> <span class="code-text"> - Marcadores também são possíveis</span>
<span class="code-number">18</span> <span class="code-text"> - Normalmente, um hífen ou asterisco é usado para o marcador, precedido</span>
<span class="code-number">19</span> <span class="code-text">   por um único espaço, com linhas em branco entre eles, mas as convenções</span>
<span class="code-number">20</span> <span class="code-text">   variam aqui</span>
<span class="code-number">21</span> <span class="code-text"></span>
<span class="code-number">22</span> <span class="code-text">Se você usa um rastreador de problemas, coloque referências a eles na parte</span>
<span class="code-number">23</span> <span class="code-text">inferior, assim:</span>
<span class="code-number">24</span> <span class="code-text"></span>
<span class="code-number">25</span> <span class="code-text">Corrige: CRBU-1984 #time 5m</span>
<span class="code-number">26</span> <span class="code-text">Veja também: CRBU-2023, CRBU-2024</span>
</pre>

