<pre>
<span class="code-number">1</span> <span class="code-text"># Bom</span>
<span class="code-number">2</span> <span class="code-text">ababab refactor: add `use` method to Credit model</span>
<span class="code-number">3</span> <span class="code-text">efefef refactor: use InventoryBackendPool to retrieve inventory backend</span>
<span class="code-number">4</span> <span class="code-text">bebebe fix: fix method name of InventoryBackend child classes</span>
</pre>

