<pre>
<span class="code-number">1</span> <span class="code-text"># Ruim</span>
<span class="code-number">2</span> <span class="code-text">fix this</span>
<span class="code-number">3</span> <span class="code-text"></span>
<span class="code-number">4</span> <span class="code-text">fix stuff</span>
<span class="code-number">5</span> <span class="code-text"></span>
<span class="code-number">6</span> <span class="code-text">agora vai</span>
<span class="code-number">7</span> <span class="code-text"></span>
<span class="code-number">8</span> <span class="code-text">change stuff</span>
<span class="code-number">9</span> <span class="code-text">adjust css</span>
</pre>

