<pre>
<span class="code-number">1</span> <span class="code-text"># Good</span>
<span class="code-number">2</span> <span class="code-text">fix: fix name method of InventoryBackend child classes</span>
<span class="code-number">3</span> <span class="code-text"></span>
<span class="code-number">4</span> <span class="code-text">Classes derived from Inventory Backend were not respecting the base</span>
<span class="code-number">5</span> <span class="code-text">class interface.</span>
<span class="code-number">6</span> <span class="code-text"></span>
<span class="code-number">7</span> <span class="code-text">Previously worked because cart was calling the implementation</span>
<span class="code-number">8</span> <span class="code-text">incorrectly.</span>
</pre>

