<pre>
<span class="code-number">1</span> <span class="code-text">$ git checkout main</span>
<span class="code-number">2</span> <span class="code-text">$ git reset --hard origin/main</span>
<span class="code-number">3</span> <span class="code-text">$ git fetch origin --prune</span>
<span class="code-number">4</span> <span class="code-text">$ git merge</span>
<span class="code-number">5</span> <span class="code-text">$ git checkout -b &lt;your-branch-name&gt;</span>
</pre>
