<div class="comment-block">
    <p><span class="code-text">Outra saída possível poderá ser uma mensagem de erro indicando que foram encontrados conflitos ao tentar mesclar o conteúdo dos arquivos.</span></p>
    <p><span class="code-text">Nesse caso, deve-se:</span></p>
    <ol>
        <li><span class="code-text">Resolver todos os conflitos manualmente;</span></li>
        <li><span class="code-text">Marcá-los como resolvidos com <code>git add &lt;arquivos-com-conflitos&gt;</code> ou <code>git rm &lt;arquivos-com-conflitos&gt;</code></span></li>
        <li><span class="code-text">E então acionar o comando <code>git rebase --continue</code>.</span></li>
    </ol>
    <p><span class="code-text"></span></p>
    <p><span class="code-text">Pode-se também pular o commit atual executando <code>git rebase --skip</code>.</span></p>
    <p><span class="code-text"></span></p>
    <p><span class="code-text">Já para abortar e voltar ao estado anterior ao "git rebase", execute <code>git rebase --abort</code>.</span></p>
</div>
