<pre>
<span class="code-number"> 1</span> <span class="code-text">$ cd &lt;caminho-para-a-pasta-do-repositório&gt;</span>
<span class="code-number"> 2</span> <span class="code-text"></span>
<span class="code-number"> 3</span> <span class="code-text">$ git checkout main</span>
<span class="code-number"> 4</span> <span class="code-text">$ git reset --hard origin/main</span>
<span class="code-number"> 5</span> <span class="code-text">$ git fetch --all</span>
<span class="code-number"> 6</span> <span class="code-text">$ git merge</span>
<span class="code-number"> 7</span> <span class="code-text"></span>
<span class="code-number"> 8</span> <span class="code-text">$ git checkout &lt;nome-da-ramificação-de-trabalho&gt;</span>
<span class="code-number"> 9</span> <span class="code-text">$ git rebase main</span>
<span class="code-number">10</span> <span class="code-text">$ git push -f</span>
</pre>
