<pre>
<span class="code-number">2</span> <span class="code-text">Counting objects: 3,"done.</span>
<span class="code-number">3</span> <span class="code-text">Delta compression using up to 4 threads.</span>
<span class="code-number">4</span> <span class="code-text">Compressing objects: 100% (3/3), done.</span>
<span class="code-number">5</span> <span class="code-text">Writing objects: 100% (3/3), 336 bytes | 0 bytes/s, done.</span>
<span class="code-number">6</span> <span class="code-text">Total 3 (delta 0), reused 0 (delta 0)</span>
<span class="code-number">7</span> <span class="code-text">To https://github.com/path/to/repo.git</span>
<span class="code-number">8</span> <span class="code-text">    a1f29a6..79c0e80 nome-da-ramificação-de-trabalho -> nome-da-ramificação-de-trabalho</span>
<span class="code-number">9</span> <span class="code-text">Branch nome-da-ramificação-de-trabalho set up to track remote branch nome-da-ramificação-de-trabalho from origin.</span>
</pre>
