<pre>
<span class="code-number">2</span> <span class="code-text">On branch nome-da-ramificação-de-trabalho</span>
<span class="code-number">3</span> <span class="code-text">Your branch is ahead of 'origin/nome-da-ramificação-de-trabalho' by 1 commit.</span>
<span class="code-number">4</span> <span class="code-text">  (use "git push" to publish your local commits)</span>
<span class="code-number">5</span> <span class="code-text">  nothing to commit, working directory clean</span>
</pre>
