<pre>
<span class="code-number">1</span> <span class="code-text"># Please enter the commit message for your changes. Lines starting</span>
<span class="code-number">2</span> <span class="code-text"># with '#' will be ignored, and an empty message aborts the commit.</span>
<span class="code-number">3</span> <span class="code-text"># On branch nome-da-ramificação-de-trabalho</span>
<span class="code-number">4</span> <span class="code-text"># Your branch is up-to-date with 'origin/nome-da-ramificação-de-trabalho'.</span>
<span class="code-number">5</span> <span class="code-text">#</span>
<span class="code-number">6</span> <span class="code-text"># Changes to be committed:</span>
<span class="code-number">7</span> <span class="code-text">#       modified:   wip.php</span>
<span class="code-number">8</span> <span class="code-text">#</span>
</pre>
