<div class="row">
    <div class="card-body">
        <a href="https://github.com/mshibata-nuvemshop" target="_blank" rel="noopener"><img class="img-thumbnail" src="https://github.com/mshibata-nuvemshop.png" alt="squad member" title="Maiki Shibata" width="80" height="80" style="max-width:100%;"></a>
        <a href="https://github.com/LuizHonorato" target="_blank" rel="noopener"><img class="img-thumbnail" src="https://github.com/LuizHonorato.png" alt="squad member" title="Luiz Honorato" width="80" height="80" style="max-width:100%;"></a>
        <a href="https://github.com/jonathanbraznuvem" target="_blank" rel="noopener"><img class="img-thumbnail" src="https://github.com/jonathanbraznuvem.png" alt="squad member" title="Jonathan Braz" width="80" height="80" style="max-width:100%;"></a>
        <a href="https://github.com/marianadasilvanuvem" target="_blank" rel="noopener"><img class="img-thumbnail" src="https://github.com/marianadasilvanuvem.png" alt="squad member" title="Mariana da Silva" width="80" height="80" style="max-width:100%;"></a>
        <a href="https://github.com/jonatanreginato" target="_blank" rel="noopener"><img class="img-thumbnail" src="https://github.com/jonatanreginato.png" alt="squad member" title="Jonatan N. Reginato" width="80" height="80" style="max-width:100%;"></a>
    </div>
</div>
