name: "Feature request"
description: "Request a feature or enhancement"
labels: ["feature requested"]
body:
  - type: "markdown"
    attributes:
      value: |
        Thanks for submitting an enhancement or feature request 😄!

        Please search open/closed issues before submitting. Someone might have asked the same thing before 😉!
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please describe your request in one or two sentences"
    validations:
      required: true
  - type: "textarea"
    id: "justification"
    attributes:
      label: "Problem statement/justification"
      description: |
        Please provide valid reason(s) why this should be added. If this feature is related to a problem you've noticed,
        mention it as well.
    validations:
      required: true
  - type: "textarea"
    id: "proposed-solution"
    attributes:
      label: "Proposed solution"
      description: |
        Describe your idea for a solution to the problem.
    validations:
      required: true
  - type: "textarea"
    id: "alternatives"
    attributes:
      label: "Alternatives"
      description: |
        What alternative solutions have you considered before making this request?
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |
        What resources (links, screenshots, etc.) do you have to assist this effort?
