<?php

declare(strict_types=1);

$status = isset($status) ? $this->e($status) : 400;
$reason = isset($reason) ? $this->e($reason) : '';

$response = [
    'message' => "We encountered a $status $reason error.",
    'data'    => [
        'description' => isset($error) ? $error->getMessage() : null,
    ],
];

if (getenv('APPLICATION_ENV') === 'development') {
    $response['data'] = array_merge($response['data'], [
        'code' => isset($error) ? $this->e($error->getCode()) : null,
        'file' => isset($error) ? $this->e($error->getFile()) : null,
        'line' => isset($error) ? $this->e($error->getLine()) : null,
    ]);
}

header('Content-Type: application/json');

try {
    echo json_encode($response, JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT);
} catch (JsonException $e) {
    echo $e->getCode() . ':' . $e->getMessage();
}
