<nav>
    <div class="resource-group">
        <div class="heading">
            <div class="chevron"><em class="open fa fa-angle-down"></em></div>
            <a href="#top">Content</a>
        </div>
        <div class="collapse-content">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/team">Team</a></li>
                <li><a href="/resources">Resources</a></li>
                <li><a href="/setup">Development Environment Setup</a></li>
                <li><a href="/contributing">Contributing</a>
                    <ul>
                        <li><a href="/conduct-code">Conduct Code</a></li>
                        <li><a href="/source-code">Source Code</a></li>
                        <li><a href="/coding-standards">Coding Standards</a></li>
                        <li><a href="/commit-standards">Commit Standards</a></li>
                        <li><a href="/contribution-guide">Contribution Guide</a></li>
                        <li><a href="/contribution-cheatsheet">Contribution Cheatsheet</a></li>
                    </ul>
                </li>
                <li><a href="/documentation">API documentation</a></li>
                <li><a href="/license">License</a></li>
                <li><a href="/test-coverage/unit">Unit Test Coverage</a></li>
                <li><a href="/test-coverage/integration">Integration Test Coverage</a></li>
            </ul>
        </div>
    </div>
</nav>
