name: Release Drafter
on:
  push:
    branches:
      - production
      - staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
